//
// Module timer_tutorial.timer.struct
//
// Created:
//          by - User.UNKNOWN (VBOX)
//          at - 04:07:26 14.04.2022
//
// Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
//

`resetall
`timescale 1ns/10ps
module timer( 
   clk, 
   d, 
   reset, 
   start, 
   stop, 
   alarm, 
   high, 
   low
);


// Internal Declarations

input        clk;
input  [9:0] d;
input        reset;
input        start;
input        stop;
output       alarm;
output [3:0] high;
output [3:0] low;


wire        clk;
wire [9:0]  d;
wire        reset;
wire        start;
wire        stop;
wire        alarm;
wire [3:0]  high;
wire [3:0]  low;

// Local declarations
reg[3:0] d_out;


// Internal signal declarations
wire       beep;
wire       clear;
wire [3:0] dat_in;
wire       hold;
wire       load;
wire       rst;
wire       zero;


// Instances 
CONTROL U_0( 
   .clk   (clk), 
   .d     (d), 
   .reset (reset), 
   .rst   (rst), 
   .start (start), 
   .stop  (stop), 
   .zero  (zero), 
   .beep  (beep), 
   .clear (clear), 
   .hold  (hold), 
   .load  (load)
); 

COUNTER U_1( 
   .clear  (clear), 
   .clk    (clk), 
   .dat_in (dat_in), 
   .hold   (hold), 
   .load   (load), 
   .high   (high), 
   .low    (low), 
   .zero   (zero)
); 

// HDL Embedded Block 1 DtoB

// HDL Embedded Text Block 2 OR1
// OR1 2
assign alarm = hold | beep;
                                        

endmodule // timer

